### PR TITLE
Bugfix/scan slice alias

### LINKED ISSUE #96: store.Find fails when the struct has a property that is an alias of a slice
store.Find fails when the struct has a property that is an alias of a slice.
```
Error:		func (assert.PanicTestFunc)(0x4a9080) should not panic
Panic value:	sql: Scan error on column index 3: pq: parsing array element index 0: pq: scanning to string is not implemented; only sql.Scanner
```
If the struct has contain (not `empty` content) under a property that is an Alias of a slice, any Find that reach that struct will fail.
If the property is empty, the Find will not fail.

Tests in PR https://github.com/src-d/go-kallax/pull/97

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #96

### CODE REVIEW

**Comment by erizocosmico** [comment]
Don't merge yet, I discovered it needs a bit more of work before being fully complete.

**Comment by Serabe** [comment]
Please, ping when it is ready.

**Comment by erizocosmico** [comment]
Will do

**Comment by erizocosmico** [comment]
Can be reviewed now @dpordomingo @Serabe

**Pull request merged**
