### PR TITLE
Swap satori/go.uuid to gofrs/uuid

### LINKED ISSUE #286: Swap out satori/go.uuid for gofrs/uuid
The satori UUID library isn't being maintained, and has a number of major issues with generating random UUIDs in the latest iteration. It'd be a good idea to swap it out for https://github.com/gofrs/uuid, which should be a drop-in community-maintained replacement without the bugs.

I currently have this in my `Gopkg.toml` to hack it in my projects for now:

```toml
[[constraint]]
  name = "github.com/satori/go.uuid"
  source = "https://github.com/gofrs/uuid.git"
```

### PR DESCRIPTION
**Pull request by smacker**
Fix #286

It still supports `satori/go.uuid` in the generator though.

### CODE REVIEW

**Comment by roobre** [comment]
Tests seem to pass and the changes seem small and concise. However, it probably needs some manual testing to ensure it doesn't break existing setups.

**Comment by smola** [comment]
What about adding a test that checks that generator is ok both with satori/go.uuid and gofrs/uuid?

**Comment by giautm** [comment]
Hi, any update on this?

**Comment by smola** [comment]
@smacker Checking that it still works with satori/go.uuid, but now I realize that might already be covered?

**Comment by giautm** [comment]
This issues blocking me to use this package, because I don't want to use an unmaintained project (with a bug in generating UUID).

**Comment by smacker** [comment]
@smola I pushed a test, is it what you suggested?

**Comment by smola** [comment]
@smacker Yep.

**Pull request merged**
